<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MD-1MB0RG2" name="com.magic.web.tests.FailTest" tests="1" failures="0" timestamp="4 Jun 2019 08:01:31 GMT" time="0.002" errors="1">
  <testcase name="failTest" time="0.002" classname="com.magic.web.tests.FailTest">
    <error type="java.lang.IllegalArgumentException" message="FailedTestsScreenshots does not exist">
      <![CDATA[java.lang.IllegalArgumentException: FailedTestsScreenshots does not exist
	at org.apache.commons.io.FileUtils.verifiedListFiles(FileUtils.java:1741)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1716)
	at com.magic.utils.GenericUtil.cleanUpFolder(GenericUtil.java:63)
	at com.magic.web.TestBase.beforeSuite(TestBase.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- failTest -->
</testsuite> <!-- com.magic.web.tests.FailTest -->
